# Generated by Django 5.2.3 on 2025-06-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
