# Generated by Django 5.2.3 on 2025-07-12 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_payments_options_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="payment_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payments",
            name="status",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payments",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
