# Generated by Django 5.2.3 on 2025-07-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_payments_payment_link_payments_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
