# Generated by Django 5.2.3 on 2025-07-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_payments_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="payments",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
