# Generated by Django 5.2.3 on 2025-06-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="previews/courses/",
                verbose_name="Превью",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="previews/lessons/",
                verbose_name="Превью",
            ),
        ),
    ]
