# Generated by Django 5.2.3 on 2025-07-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_subscriptions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptions",
            options={
                "ordering": ["course", "user"],
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
    ]
