# Generated by Django 5.2.3 on 2025-07-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_subscriptions_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["id"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["id"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.AlterModelOptions(
            name="subscriptions",
            options={
                "ordering": ["id"],
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
    ]
