# Generated by Django 5.2.3 on 2025-07-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_alter_course_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
